In [1]:
#Gọi thư viện
import numpy as np

#Tạo 1 ma trận các số nguyên ngẫu nhiên trong khoảng từ 1 - 100
matran_A = np.random.randint(1, 100, (10, 15))

print(matran_A)
print('Kích thước của ma trận:', matran_A.shape)

[[61 99 28 53 18 44 15 87 33 17 12 51 45 61 60]
 [43  3 19 65 28 25 88 69 91 10 93 41 92  7 53]
 [32 63 87 89 91 38 12 27 40  8 91 86 20 93 68]
 [17 36 54 64 22 72 24 24 60 82 89 73 91 78 14]
 [78 71 97 14 55 67 88 62 75 60 61 71 68 19  2]
 [33 21 75 79  4 49 49 74 68 57 16 30 74 31 85]
 [47 18 80 73 15 72 63 38  4  8  8  2 98 75 30]
 [45 15 99 76 19 29 12 89 42 77 97 34 51 84 86]
 [97 44 17 35 25 24 66 29 88 50  5 86 74 20 86]
 [18 22 67 30 78  2 36 38 45 86 50  5 10 76 37]]
Kích thước của ma trận: (10, 15)


In [10]:
#Tách ma trận con số 1: lấy tất cả các hàng và 10 cột đầu tiên
matran_A1 = matran_A[10:]
matran_A1

array([], shape=(0, 15), dtype=int32)

In [3]:
#Tách ma trận con số 2: lấy tất cả các hàng và 5 cột cuối cùng
matran_A2 = matran_A[:,10:]
matran_A2

array([[12, 51, 45, 61, 60],
       [93, 41, 92,  7, 53],
       [91, 86, 20, 93, 68],
       [89, 73, 91, 78, 14],
       [61, 71, 68, 19,  2],
       [16, 30, 74, 31, 85],
       [ 8,  2, 98, 75, 30],
       [97, 34, 51, 84, 86],
       [ 5, 86, 74, 20, 86],
       [50,  5, 10, 76, 37]])

In [11]:
#Cách truy cập dữ liệu trong numpy
hangdau = matran_A[0,:]
hangdau

In [12]:
hangcuoi = matran_A[-1,:]
hangcuoi

array([18, 22, 67, 30, 78,  2, 36, 38, 45, 86, 50,  5, 10, 76, 37])

In [13]:
phantu0 = matran_A[0,0]
phantu0

61

In [16]:
phantucuoi = matran_A[-1,-1]
phantucuoi

37

<h1>2. Ôn tập matplotlib</h1>

In [15]:
#Gọi thư viện 
import matplotlib.pyplot as plt

ten_khoa_x = ['K64', 'K65', 'K66', 'K67', 'K68'] 
so_hs_y = [450, 570, 1520, 820, 200]

In [26]:
#Vẽ biểu đồ dạng cột 
plt.bar(ten_khoa_x, so_hs_y, color='brown')

plt.title('BIỂU ĐỒ THỂ HIỆN SỐ LƯỢNG SINH VIÊN THEO TỪNG KHÓA') 
plt.grid(ls='--') 
plt.xlabel('Khóa') 
plt.ylabel('Số lượng')

plt.show()


NameError: name 'plt' is not defined

In [21]:
#Vẽ biểu đồ dạng hàng
plt.barh(ten_khoa_x, 
        so_hs_y,
        color='brown')

plt.title('BIỂU ĐỒ THỂ HIỆN SỐ LƯỢNG SINH VIÊN THEO TỪNG KHÓA')
plt.grid(ls='--')
plt.xlabel('Khóa')
plt.ylabel('Số lượng')

plt.show()


NameError: name 'plt' is not defined

In [23]:
#Vẽ biểu đồ dạng đường
plt.plot(ten_khoa_A,
        so_hs_y,
        'b-o',ms=10)

plt.title('BIỂU ĐỒ THỂ HIỆN SỐ LƯỢNG SINH VIÊN THEO TỪNG KHÓA')
plt.grid(ls='--')
plt.xlabel('Khóa')
plt.ylabel('Số lượng')

plt.show()

NameError: name 'plt' is not defined

In [25]:
#Vẽ biểu đồ tròn
plt.pie(so_hs_y,
       labels=ten_khoa_x,
       autopct='%.1f%%',
       wedgeprops=dict(width=0.7, edgecolor='w'))

plt.title('BIỂU ĐỒ THỂ HIỆN SỐ LƯỢNG SINH VIÊN THEO TỪNG KHÓA')
plt.show()

NameError: name 'plt' is not defined

In [28]:
import pandas as pd
df_movie1 = pd.read_excel('Data/Data_Movies.xlsx',
                         sheet_name='1900s')
df_movie1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Title                        1338 non-null   object 
 1   Year                         1338 non-null   int64  
 2   Genres                       1338 non-null   object 
 3   Language                     1333 non-null   object 
 4   Country                      1338 non-null   object 
 5   Content Rating               1316 non-null   object 
 6   Duration                     1338 non-null   int64  
 7   Aspect Ratio                 1308 non-null   float64
 8   Budget                       1281 non-null   float64
 9   Gross Earnings               1086 non-null   float64
 10  Director                     1338 non-null   object 
 11  Actor 1                      1338 non-null   object 
 12  Actor 2                      1338 non-null   object 
 13  Actor 3           

In [29]:
df_movie3 = pd.read_excel('Data/Data_Movies.xlsx',
                         sheet_name='2010s',
                         skiprows=3,
                         header=None)
df_movie3

0       1   \
0                               127 Hours   2010.0   
1                             3 Backyards   2010.0   
2                                       3   2010.0   
3               8: The Mormon Proposition   2010.0   
4     A Turtle's Tale: Sammy's Adventures   2010.0   
...                                    ...     ...   
1599              War & Peace                  NaN   
1600                    Wings                  NaN   
1601               Wolf Creek                  NaN   
1602        Wuthering Heights                  NaN   
1603  Yu-Gi-Oh! Duel Monsters                  NaN   

                                             2         3          4        5   \
0            Adventure|Biography|Drama|Thriller   English        USA        R   
1                                         Drama   English        USA        R   
2                          Comedy|Drama|Romance    German    Germany  Unrated   
3                                   Documentary   English        USA        R   
4                    Adventure|Animation|Family   English     France       PG   
...                                         ...       ...        ...      ...   
1599                  Drama|History|Romance|War   English         UK    TV-14   
1600                               Comedy|Drama   English        USA      NaN   
1601                      Drama|Horror|Thriller   English  Australia      NaN   
1602                              Drama|Romance   English         UK      NaN   
1603  Action|Adventure|Animation|Family|Fantasy  Japanese      Japan      NaN   

         6      7           8           9   ...       15     16     17     18  \
0      94.0   1.85  18000000.0  18329466.0  ...  11000.0  642.0  223.0  11984   
1      88.0    NaN    300000.0         NaN  ...    795.0  659.0  301.0   1884   
2     119.0   2.35         NaN     59774.0  ...     24.0   20.0    9.0     69   
3      80.0   1.78   2500000.0     99851.0  ...    191.0   12.0    5.0    210   
4      88.0   2.35         NaN         NaN  ...    783.0  749.0  602.0   3874   
...     ...    ...         ...         ...  ...      ...    ...    ...    ...   
1599    NaN  16.00         NaN         NaN  ...   1000.0  888.0  502.0   4528   
1600   30.0   1.33         NaN         NaN  ...    685.0  511.0  424.0   1884   
1601    NaN   2.00         NaN         NaN  ...    511.0  457.0  206.0   1617   
1602  142.0    NaN         NaN         NaN  ...  27000.0  698.0  427.0  29196   
1603   24.0    NaN         NaN         NaN  ...      0.0    NaN    NaN      0   

         19   20      21     22     23   24  
0     63000  0.0  279179  440.0  450.0  7.6  
1        92  0.0     554   23.0   20.0  5.2  
2      2000  0.0    4212   18.0   76.0  6.8  
3         0  0.0    1138   30.0   28.0  7.1  
4         0  2.0    5385   22.0   56.0  6.1  
...     ...  ...     ...    ...    ...  ...  
1599  11000  1.0    9277   44.0   10.0  8.2  
1600   1000  5.0    7646   56.0   19.0  7.3  
1601    954  0.0     726    6.0    2.0  7.1  
1602      0  2.0    6053   33.0    9.0  7.7  
1603    124  0.0   12417   51.0    6.0  7.0  

[1604 rows x 25 columns]